
<?php $__env->startSection('content'); ?>
<h1 class="mb-4 text-2xl font-bold">Review Pengajuan Judul</h1>
<div class="mb-4 rounded bg-white p-4 shadow"><h2 class="font-bold"><?php echo e($title->title); ?></h2><p class="text-sm text-slate-500">Mahasiswa: <?php echo e($title->student->name); ?></p><p class="mt-3 whitespace-pre-line"><?php echo e($title->background); ?></p></div>
<form method="POST" action="<?php echo e(route('titles.review',$title)); ?>" class="rounded bg-white p-4 shadow">
<?php echo csrf_field(); ?>
<label class="mb-2 block font-semibold">Status</label><select name="status" class="mb-4 w-full rounded border p-2" required><?php $__currentLoopData = ['diajukan','disetujui','ditolak','revisi']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($s); ?>" <?php if(old('status',$title->status)==$s): echo 'selected'; endif; ?>><?php echo e(strtoupper($s)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select>
<label class="mb-2 block font-semibold">Dosen Pembimbing 1</label><select name="supervisor_id" class="mb-4 w-full rounded border p-2"><option value="">- Pilih dosen -</option><?php $__currentLoopData = $dosens; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $d): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($d->id); ?>" <?php if(old('supervisor_id',$title->supervisor_id)==$d->id): echo 'selected'; endif; ?>><?php echo e($d->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select>
<label class="mb-2 block font-semibold">Dosen Pembimbing 2</label><select name="supervisor_id" class="mb-4 w-full rounded border p-2"><option value="">- Pilih dosen -</option><?php $__currentLoopData = $dosens; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $d): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($d->id); ?>" <?php if(old('supervisor_id',$title->supervisor_id)==$d->id): echo 'selected'; endif; ?>><?php echo e($d->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select>
<label class="mb-2 block font-semibold">Catatan Jurusan</label><textarea name="notes" rows="5" class="mb-4 w-full rounded border p-2"><?php echo e(old('notes',$title->notes)); ?></textarea>
<button class="rounded bg-indigo-600 px-4 py-2 text-white">Simpan Review</button>
</form>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\VITRA\SIM-SKRIPSI\vitra-skripsi-laravel-fixed\resources\views/titles/review.blade.php ENDPATH**/ ?>